using System.Collections.Generic;
using System.IO;
using System.Reflection;

namespace Stellar.Infrastructure.UI;

/// <summary>
/// Loads the embedded launcher icon set (raw PNG bytes). Used by Host to
/// populate <c>LauncherEntry.IconPng</c> / <c>MenuButtonSpec.IconPng</c> for
/// the framework's own entries + rail button, and by the launcher window for
/// its chrome glyphs (pin star, mode toggle). Bytes are cached per name.
///
/// <para>Names (no extension): the 8 entry icons —
/// <c>stellar, settings, plugins, hotkeys, theme, layout, gameui, about</c> —
/// and the 4 chrome glyphs — <c>star, star_outline, mode_grid, mode_list</c>.
/// Generated by <c>tools/gen-launcher-icons.py</c>.</para>
/// </summary>
internal static class LauncherIcons
{
    private const string Prefix = "Stellar.Infrastructure.icons.";
    private static readonly Dictionary<string, byte[]?> _cache = new();
    private static readonly object _gate = new();

    /// <summary>Raw PNG bytes for <paramref name="name"/> (no extension), or null if absent.</summary>
    public static byte[]? Get(string name)
    {
        lock (_gate)
        {
            if (_cache.TryGetValue(name, out var cached)) return cached;
            var bytes = Load(name);
            _cache[name] = bytes;
            return bytes;
        }
    }

    private static byte[]? Load(string name)
    {
        try
        {
            var asm = typeof(LauncherIcons).Assembly;
            var resource = Prefix + name + ".png";
            using var s = asm.GetManifestResourceStream(resource) ?? FindBySuffix(asm, name);
            if (s != null)
            {
                using var ms = new MemoryStream();
                s.CopyTo(ms);
                return ms.ToArray();
            }
            return LoadFromDisk(name);   // sandbox/test fallback (resources aren't embedded in that assembly)
        }
        catch
        {
            return null;
        }
    }

    // Disk fallback for the UI sandbox: the icon PNGs are embedded resources of THIS assembly, which the
    // sandbox Unity project doesn't carry. run-ui-sandbox.sh sets STELLAR_ICONS_DIR so the real LauncherView
    // renders true icons there (no divergent hand-built copy). Unset in-game → no-op, embedded resources win.
    private static byte[]? LoadFromDisk(string name)
    {
        var dir = System.Environment.GetEnvironmentVariable("STELLAR_ICONS_DIR");
        if (string.IsNullOrEmpty(dir)) return null;
        var path = Path.Combine(dir, name + ".png");
        return File.Exists(path) ? File.ReadAllBytes(path) : null;
    }

    // Fallback if the logical-name convention differs from the build's default.
    private static Stream? FindBySuffix(Assembly asm, string name)
    {
        var suffix = "icons." + name + ".png";
        foreach (var res in asm.GetManifestResourceNames())
            if (res.EndsWith(suffix, System.StringComparison.Ordinal))
                return asm.GetManifestResourceStream(res);
        return null;
    }
}
